### ISSUE TITLE
Blokuje się na logowaniu

### ISSUE THREAD

**Issue by JERZAO** [UnoMartino/Auto.Ling#2]
Po odpaleniu skryptu odpala przeglądarkę wchodzi na stronę instalinga, loguje się, przechodzi na główną stronę instalinga(nie zalogowało się), i tyle, nic więcej się nie dzieje, używałem go przed dłuższy czas bez zarzutów a teraz nie chce się zalogować.

**Comment by UnoMartino** [comment]
Której wersji używasz? W 2.3.0 zostało to naprawione. Instaling wprowadził zabezpieczenie przed botami.
